app = "calendar-tetromino-grpc"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[env]
PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    port = 50051
    handlers = []  # no HTTP handlers because gRPC is not HTTP

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
